INCLUDE_DIR=./includes/

RBT=./src/RBT.cpp
rbt: $(RBT)
	g++ -Wall $(RBT) -I$(INCLUDE_DIR) -o bin/rbt_test

AVL=./src/AVLTree.cpp
avl: $(AVL)
	g++ -Wall $(AVL) -I$(INCLUDE_DIR) -o bin/avl

VECTORN=./src/VectorN.cpp
vecn: $(VECTORN)
	g++ -Wall $(VECTORN) -I$(INCLUDE_DIR) -o bin/vecn
